seleniumhub:
  image: selenium/hub
  ports: 
    - 4444:4444

chromenode:
  image: selenium/node-chrome-debug
  ports:
    - 4577
  links:
    - seleniumhub:hub

firefoxnode:
  image: selenium/node-firefox-debug
  ports:
    - 4578
  links:
    - seleniumhub:hub